CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(512) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id)
  );

  CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(512) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
    );

  CREATE TABLE IF NOT EXISTS events(
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        annotation VARCHAR NOT NULL,
        category_id BIGINT,
        initiator_id BIGINT,
        created_on VARCHAR(512) NOT NULL,
        description VARCHAR NOT NULL,
        event_date VARCHAR(512) NOT NULL,
        location_id BIGINT,
        paid BOOLEAN NOT NULL,
        participant_limit BIGINT,
        request_moderation BOOLEAN,
        published_on VARCHAR(512),
        state VARCHAR(512),
        title VARCHAR(512),
        CONSTRAINT pk_events PRIMARY KEY (id)
        );

  CREATE TABLE IF NOT EXISTS locations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      lon FLOAT NOT NULL,
      lat FLOAT NOT NULL,
      CONSTRAINT pk_locations PRIMARY KEY (id)
      );

  CREATE TABLE IF NOT EXISTS compilations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        event_ids VARCHAR(512) NOT NULL,
        pinned BOOLEAN NOT NULL,
        title VARCHAR(512) NOT NULL,
        CONSTRAINT pk_compilations PRIMARY KEY (id)
        );

  CREATE TABLE IF NOT EXISTS requests (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          status VARCHAR(512) NOT NULL,
          created VARCHAR(512) NOT NULL,
          event_id VARCHAR(512) NOT NULL,
          requester_id VARCHAR(512) NOT NULL,
          CONSTRAINT pk_requests PRIMARY KEY (id)
          );

  CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(512) NOT NULL,
  author_name VARCHAR(512) NOT NULL,
  created VARCHAR(512) NOT NULL,
  event_id BIGINT NOT NULL,
  CONSTRAINT pk_comments PRIMARY KEY (id)
);



