CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(64) NOT NULL,
  email VARCHAR(64) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id)
  );

  CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
    );

  CREATE TABLE IF NOT EXISTS events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        annotation VARCHAR(64) NOT NULL,
        category_id BIGINT NOT NULL,
        initiator_id BIGINT NOT NULL,
        createdOn VARCHAR(64) NOT NULL,
        description VARCHAR(64) NOT NULL,
        eventDate VARCHAR(64) NOT NULL,
        location_id BIGINT NOT NULL,
        paid BOOLEAN NOT NULL,
        participantLimit BIGINT,
        requestModeration BOOLEAN,
        publishedOn VARCHAR(64),
        state VARCHAR(64),
        title VARCHAR(64),
        CONSTRAINT pk_events PRIMARY KEY (id)
        );

  CREATE TABLE IF NOT EXISTS locations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      longitude FLOAT(64) NOT NULL,
      latitude FLOAT(64) NOT NULL,
      CONSTRAINT pk_locations PRIMARY KEY (id)
      );

  CREATE TABLE IF NOT EXISTS compilations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        eventIds VARCHAR(64) NOT NULL,
        pinned BOOLEAN NOT NULL,
        title VARCHAR(64) NOT NULL,
        CONSTRAINT pk_compilations PRIMARY KEY (id)
        );

  CREATE TABLE IF NOT EXISTS requests (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          status VARCHAR(64) NOT NULL,
          created VARCHAR(64) NOT NULL,
          event_id VARCHAR(64) NOT NULL,
          requester_id VARCHAR(64) NOT NULL,
          CONSTRAINT pk_requests PRIMARY KEY (id)
          );



